language: java
jdk:
- oraclejdk8
services:
- docker
cache:
  directories:
  - $HOME/.m2
notifications:
  email: false
  slack:
    rooms:
      secure: w5J/yet+9f+x6TV6pxo5QskP1g98rmo7X3mW1+Ziow7VOqlODr+CklYNclhfQJawjjDFGtHxBEM6amElYjblZvIZTlg6fon+ZcSGNzC6E47+Vsp5u8IUrZbQnHBFJ3tED10daGMeLCuNxhwE276n+/J7s4KjYfMbMSvFkQWZxjMHRRsZU1H2WOLYCiAMlw3Nq4Gbze1b4TPJltQrVBuWsLfUuEDWZuI/juCSYvF2k+eAoT62L6GHxSpk3xqAfjBeQ+W1bsnOVW3mmXKioYTkqc89wXUvTY1oIVnWk6hP0rMLG9m7euIejkjf4m2w0ju5p+Y6YaXieQr/LwfQ4WomxOSwe4yV9VdPoOnfjLm7E1lNkGvtUGHOA5RX/NDrXlz4T+oTklkBw2wHTQcGucLYYUq9hm6f/0+h0SDQq/RF7T74vQt5E8c4lnWvsVQryqLlQcttsMoYtOg1oeUUq345IiVr7pqtqy0JDUMI2+Alm7IYqckrBIIqFwIg941UPMvzX9XMMV3lyKldK4gmsQSvmYF+fa0pkOPvFPb7viTgf/fG/jQqGazEG7GUbg+FJjipYkaZ91lN+bPp/8b5IkSaVWoW0O3t04PIIfoIpUylICLkRG8CfiAKSoSrog3eHi0ZNWhKInGWXlUxmsAe2y02JnpJmKkS9nwY9LKgbv7CkcQ=
    on_success: never
    on_failure: always
    on_pull_requests: false
install:
- mvn install -Dmaven.main.skip=true -Dmaven.test.skip=true -DskipTests -DskipITs
  -Dmaven.javadoc.skip=true -Ddocker.skip=true -B -V
script:
- mvn clean test cobertura:cobertura --fail-at-end
after_success:
- mvn coveralls:report
- if [ "$TRAVIS_BRANCH" == "master" ]; then mvn package -Dmaven.main.skip=true -Dmaven.test.skip=true
  -DskipTests -DskipITs -Dmaven.javadoc.skip=true -Ddocker.skip=true; mvn docker:build
  -pl docker; mvn docker:push -pl docker -Ddocker.username=${DOCKER_USERNAME} -Ddocker.password=${DOCKER_PASSWORD};
  fi
